### ISSUE TITLE
Change annotaion list in index to key-value pair (dictionary) annotations.

### ISSUE THREAD

**Issue by 10zinten** [OpenPecha-dev/openpecha-toolkit#72]
Currently annotations in index are list and also parts are list. For eg:

https://github.com/OpenPecha/P000001/blob/561c31601d9970549ff6dc41b61ae05b5d4357c8/P000001.opf/index.yml#L5-L21
```yaml
annotations:
  - id: 51f58796058b461ab32f3c972ee5417c
    work: T1
    parts:
      - id: 3cbe647abf404688a79c24d14742826c
        work: T1-1
        span:
          - vol: base/v001
            span:
              start: 28
              end: 396711
      - id: 4993722a64084f1da94b10ce89482014
        work: T1-2
        span:
          - vol: base/v001
            span:
              start: 396712
              end: 67199
```
Since we have already adopted annotations as key-value pair (dictionary) for layers. Lets follow the same for index annotations. Like this
```yaml
annotations:
  51f58796058b461ab32f3c972ee5417c:
    work: T1
    parts:
      3cbe647abf404688a79c24d14742826c:
        work: T1-1
        span:
          - vol: base/v001
            span:
              start: 28
              end: 396711
      4993722a64084f1da94b10ce89482014:
        work: T1-2
        span:
          - vol: base/v001
            span:
              start: 396712
              end: 67199
```
